### ISSUE TITLE
Please make sure that '/opt/panako/dbs/nfft_panako_db.lck' is writable.

### ISSUE THREAD

**Issue by julianterzyk** [Pixelartist/docker-panako#1]
Hey Pixelartist. Thx first of all for hosting that Panako container. I ran into an issue after mounting the container, when trying to run something like 'panako store testfile.mp3', saying 

'Could not create a lock file for the database.'
'Please make sure that '/opt/panako/dbs/nfft_panako_db.lck' is writable.' 

I looked into the /opt/panako/ directory and did not see any directory named dbs. 

Do you have any idea what is going on there? Is it a docker permission issue maybe?

Cheers,
Julian

**Comment by ManuelAudibene** [comment]
Hello Julian, thanks for your request. Since this project is very very niche and targeted, I did not really put much attention to it. Let me clean the code and replicate your issue and solve it.

**Comment by Pixelartist** [comment]
Hello Julian, thanks for your request. Since this project is very very niche and targeted, I did not really put much attention to it. Let me clean the code and replicate your issue and solve it.

**Comment by julianterzyk** [comment]
Hey Manuel,

thx so much for the quick response! Looking forward to hearing from you. And btw: the same issue happened to me when I installed everything locally on my Mac, which is why I also contacted the developer of Panako, see [here](https://github.com/JorenSix/Panako/issues/3).

Cheers,
Julian

**Comment by Pixelartist** [comment]
Hello again,

I fixed the issue - you now can store mp3 (or any other files) and play around with the system. I updated to the readme for at least a bare minimum of guidance.
I am really sorry that you stumbled about this - I did not know that someone would actually have an interest in it :)

**Comment by julianterzyk** [comment]
Hey there,

thx so much for the effort. Just tested it and it works! I basically tried the same fix on my local machine creating the dir /opt/panako/dbs, which did not exist. This did not work, so I'm surprised this was the solution here. But really cool that you reacted so fast. Will play around with that fingerprinter tomorrow.

Cheers,
Julian
